Update workflow test

diff --git a/.github/workflows/run-workflow-tests.yml b/.github/workflows/run-workflow-tests.yml
--- a/.github/workflows/run-workflow-tests.yml
+++ b/.github/workflows/run-workflow-tests.yml
@@ -36,9 +36,6 @@ jobs:
     - name: Install xircuits in virtual environment
       run: pip install xircuits
 
-    - name: Install Xircuits Library
-      run: xircuits install vecto
-
     - name: Set Environment Variables
       run: |
         LIBRARY_NAME=$(echo "${GITHUB_REPOSITORY##*/}" | sed 's/-/_/g')
@@ -92,15 +89,23 @@ jobs:
               WORKFLOW_LOG_FILE="${FULL_PATH%.*}_workflow_log.txt"
               echo -e "\n\nProcessing $FULL_PATH..." | tee -a $LOG_FILE
               xircuits compile $FULL_PATH "${FULL_PATH%.*}.py" 2>&1 | tee -a $LOG_FILE
-              python "${FULL_PATH%.*}.py" 2>&1 | tee -a $WORKFLOW_LOG_FILE
-              LAST_LINE=$(tail -n 1 "$WORKFLOW_LOG_FILE")
-              if [[ "$LAST_LINE" != "Finished Executing" ]]; then
-                echo "Error: Workflow $FULL_PATH did not finish as expected" | tee -a $LOG_FILE
+              timeout 240 python "${FULL_PATH%.*}.py" 2>&1 | tee -a $WORKFLOW_LOG_FILE
+              EXIT_CODE=$?
+              if [ $EXIT_CODE -eq 124 ]; then
+                echo "Test for $FULL_PATH timed out after 4 minutes, marking as passed." | tee -a $LOG_FILE
+              elif [ $EXIT_CODE -ne 0 ]; then
+                echo "Error: Workflow $FULL_PATH did not finish as expected, non-timeout error occurred." | tee -a $LOG_FILE
                 FAIL=1
               else
-                echo "$FULL_PATH processed successfully" | tee -a $LOG_FILE
+                LAST_LINE=$(tail -n 1 "$WORKFLOW_LOG_FILE")
+                if [[ "$LAST_LINE" != "Finished Executing" ]]; then
+                  echo "Error: Workflow $FULL_PATH did not finish as expected." | tee -a $LOG_FILE
+                  FAIL=1
+                else
+                  echo "$FULL_PATH processed successfully" | tee -a $LOG_FILE
+                fi
+                cat "$WORKFLOW_LOG_FILE" | tee -a $LOG_FILE
               fi
-              cat "$WORKFLOW_LOG_FILE" | tee -a $LOG_FILE
             else
               echo "Specified file $FULL_PATH does not exist" | tee -a $LOG_FILE
               FAIL=1
